### ISSUE TITLE
Cannot click 'Accept Chat' button in mattermost

### ISSUE THREAD

**Issue by Si-Richards** [LiveHelperChat/mattermost#10]
v4.48
PHP 8.2
Rocky Linux

Cannot click 'Accept Chat' button in Mattermost  (does nothing)

> Sep 06 09:51:19 [Warning] [default] [default] ezcPersistentDefinitionNotFoundException Object
> (
>     [message:protected] => Could not fetch the persistent object definition for the class &#039;erLhcoreClassModelMailconvConversation&#039;. Searched for &#039;/erlhcoreclassmodelmailconvconversation.php&#039;.
>     [string:Exception:private] => ezcPersistentDefinitionNotFoundException: Could not fetch the persistent object definition for the class &#039;erLhcoreClassModelMailconvConversation&#039;. Searched for &#039;/erlhcoreclassmodelmailconvconversation.php&#039;. in /usr/share/nginx/html/lhc_web/ezcomponents/PersistentObject/src/managers/code_manager.php:85
> Stack trace:
> #0 /usr/share/nginx/html/lhc_web/ezcomponents/PersistentObject/src/handlers/load_handler.php(473): ezcPersistentCodeManager->fetchDefinition()
> #1 /usr/share/nginx/html/lhc_web/ezcomponents/PersistentObject/src/persistent_session.php(341): ezcPersistentLoadHandler->createFindQuery()
> #2 /usr/share/nginx/html/lhc_web/lib/core/lhcore/lhdbtrait.php(330): ezcPersistentSession->createFindQuery()
> #3 /usr/share/nginx/html/lhc_web/cache/compiledtemplates/7828ed291e84b5a3fd82223b552c7137.php(2): erLhcoreClassModelMailconvConversation::getList()
> #4 /usr/share/nginx/html/lhc_web/lib/core/lhcore/lhmodule.php(108): include('...')
> #5 /usr/share/nginx/html/lhc_web/lib/core/lhcore/lhmodule.php(663): erLhcoreClassModule::runModule()
> #6 /usr/share/nginx/html/lhc_web/index.php(51): erLhcoreClassModule::moduleInit()
> #7 {main}
>     [code:protected] => 0
>     [file:protected] => /usr/share/nginx/html/lhc_web/ezcomponents/PersistentObject/src/managers/code_manager.php
>     [line:protected] => 85
>     [trace:Exception:private] => Array
>         (
>             [0] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/ezcomponents/PersistentObject/src/handlers/load_handler.php
>                     [line] => 473
>                     [function] => fetchDefinition
>                     [class] => ezcPersistentCodeManager
>                     [type] => ->
>                 )
> 
>             [1] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/ezcomponents/PersistentObject/src/persistent_session.php
>                     [line] => 341
>                     [function] => createFindQuery
>                     [class] => ezcPersistentLoadHandler
>                     [type] => ->
>                 )
> 
>             [2] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/lib/core/lhcore/lhdbtrait.php
>                     [line] => 330
>                     [function] => createFindQuery
>                     [class] => ezcPersistentSession
>                     [type] => ->
>                 )
> 
>             [3] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/cache/compiledtemplates/7828ed291e84b5a3fd82223b552c7137.php
>                     [line] => 2
>                     [function] => getList
>                     [class] => erLhcoreClassModelMailconvConversation
>                     [type] => ::
>                 )
> 
>             [4] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/lib/core/lhcore/lhmodule.php
>                     [line] => 108
>                     [args] => Array
>                         (
>                             [0] => /usr/share/nginx/html/lhc_web/cache/compiledtemplates/7828ed291e84b5a3fd82223b552c7137.php
>                         )
> 
>                     [function] => include
>                 )
> 
>             [5] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/lib/core/lhcore/lhmodule.php
>                     [line] => 663
>                     [function] => runModule
>                     [class] => erLhcoreClassModule
>                     [type] => ::
>                 )
> 
>             [6] => Array
>                 (
>                     [file] => /usr/share/nginx/html/lhc_web/index.php
>                     [line] => 51
>                     [function] => moduleInit
>                     [class] => erLhcoreClassModule
>                     [type] => ::
>                 )
> 
>         )
> 
>     [previous:Exception:private] => 
>     [originalMessage] => Could not fetch the persistent object definition for the class 'erLhcoreClassModelMailconvConversation'. Searched for '/erlhcoreclassmodelmailconvconversation.php'.
> )
>

**Comment by remdex** [comment]
for sure you did not updated properly... As if you searched in the code you would find this file :)
