### ISSUE TITLE
Problem after entering settings

### ISSUE THREAD

**Issue by tjfayaz** [LiveHelperChat/mattermost#2]
Hi I've installed this module but after entering the settings it takes me to a white screen. Do you know why this might be? 

I tried to clear the cache and also removed the mattermost folder from extensions and re-installed but still it has the same problem.

![Untitled](https://user-images.githubusercontent.com/18698591/110986671-d8f80300-8365-11eb-980d-ed626d0309fe.jpg)

**Comment by remdex** [comment]
See cache/default.log 
And read this
https://doc.livehelperchat.com/docs/debug/

**Comment by remdex** [comment]
And perhaps you did not followed install instructions and forgot to install composer dependencies
