### ISSUE TITLE
Errors in Directory Paths, Getting Channel/Team IDs

### ISSUE THREAD

**Issue by GmodCentral** [LiveHelperChat/mattermost#6]
`[10-Jul-2023 09:07:50 America/Los_Angeles] Exception: We could not retrieve a channel! in /home/twolifes/domains/chatbox.twolifestyles.org/public_html/extension/mattermost/classes/erlhcoreclassMattermostValidator.php:734
Stack trace:
#0 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/cache/compiledtemplates/576395cf363d38036c2ab4f287e36ebc.php(2): erLhcoreClassMattermostValidator::suggestChannel()
#1 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/lib/core/lhcore/lhmodule.php(108): include('/home/twolifes/...')
#2 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/lib/core/lhcore/lhmodule.php(658): erLhcoreClassModule::runModule()
#3 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/index.php(50): erLhcoreClassModule::moduleInit()
#4 {main}

[10-Jul-2023 09:07:50 America/Los_Angeles] ezcBaseFilePermissionException: The file 'cache/default.log' can not be opened for writing. in /home/twolifes/domains/chatbox.twolifestyles.org/public_html/ezcomponents/EventLog/src/writers/writer_file.php:229
Stack trace:
#0 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/ezcomponents/EventLog/src/writers/writer_file.php(131): ezcLogFileWriter->openFile()
#1 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/lib/core/lhcore/lhlog.php(84): ezcLogFileWriter->__construct()
#2 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/ezcomponents/Base/src/init.php(120): erLhcoreClassLog::configureObject()
#3 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/ezcomponents/EventLog/src/log.php(243): ezcBaseInit::fetchConfig()
#4 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/lib/core/lhcore/lhlog.php(64): ezcLog::getInstance()
#5 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/lib/core/lhcore/lhmodule.php(162): erLhcoreClassLog::write()
#6 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/lib/core/lhcore/lhmodule.php(658): erLhcoreClassModule::runModule()
#7 /home/twolifes/domains/chatbox.twolifestyles.org/public_html/index.php(50): erLhcoreClassModule::moduleInit()
#8 **{main}**

[10-Jul-2023 09:10:38 America/Los_Angeles] PHP Notice:  Undefined index: team_id in /home/twolifes/domains/chatbox.twolifestyles.org/public_html/extension/mattermost/classes/erlhcoreclassMattermostValidator.php on line 643
`

**Comment by remdex** [comment]
...
cache/default.log' can not be opened for writing.

**Comment by GmodCentral** [comment]
Permissions look correct though...
![Uploading Screenshot 2023-07-10 at 9.55.00 AM.png…]()

**Comment by GmodCentral** [comment]
Permissions look correct though...
<img width="2241" alt="Screenshot 2023-07-10 at 9 55 00 AM" src="https://github.com/LiveHelperChat/mattermost/assets/94576950/e15b2257-ed27-41c8-bc24-ea965b2d9d60">

**Comment by remdex** [comment]
Error tells otherwise..

**Comment by GmodCentral** [comment]
I just reinstalled it, and now its working. Not sure what happened the first time.
Maybe some corruption, idk.
Thanks for your help!
