### ISSUE TITLE
Unable to send notification on new message

### ISSUE THREAD

**Issue by nico3dfx** [LiveHelperChat/mattermost#7]
Hi,
the extension can't sends messages anymore.
Try to update the extension to the latest version, clean LHC cache but same issue.

From Mattermost log I have only this:

`{"[censored CODE]","method":"POST","err_where":"Channel.IsValid","http_code":400,"err_details":"id=[censored ID]"}`

Any suggestion?
Current Mattermost version: 8.1.2 

Thank you.

**Comment by remdex** [comment]
I don't think so it's realted to extension. If you figureout what's the problem let me know. But none of my other clietns complained that it stopped working :)

**Comment by remdex** [comment]
If you decide to dig deeper the only file you need to investigate is this
https://github.com/LiveHelperChat/mattermost/blob/main/classes/erlhcoreclassMattermostValidator.php

**Comment by nico3dfx** [comment]
Problem solved.
Reached the limit for new channels inside Mattermost.
Configured crontab to delete old chats

Thanks
