### ISSUE TITLE
Extension not sending notifications for new form chats

### ISSUE THREAD

**Issue by rotolonico** [LiveHelperChat/mattermost#8]
Steps to reproduce:
1. Open a new chat through a form in livehelperchat
2. I receive the open chat message correctly on Mattermost
3. Clear my cookies and attempt to open another chat
4. On livehelperchat the client gets back to a page with the messages from the previous chat (I am guessing somehow livehelperchat still remembers this client and keeps using the same chat instance?)
5. No new chat is started on mattermost and the old chat no longer works (new messages from the client & the operators are not being sent/received)

Any idea what I am doing wrong or if there's a way to make livehelperchat not reuse same chat sessions when you send a new form?

**Comment by remdex** [comment]
Just disable old chat reopen.

https://doc.livehelperchat.com/docs/chat/configuration#reopen-chat-functionality-enabled
