### ISSUE TITLE
Receiving from messages in Mattermost but can't send

### ISSUE THREAD

**Issue by nickian** [LiveHelperChat/mattermost#9]
I installed the extension and it works fine when starting a chat. The notification comes through to accept and create a channel on Mattermost, but when I submit a message in Mattermost, it doesn't come through to LiveChatHelper. It's just working in one direction.

I don't see anything relevant in the Mattermost Server Logs. My Audit Log is also empty.

Has this been tested with the newest version of Mattermost (9.7.3)?

**Comment by remdex** [comment]
If it does not go to lhc check that mattermost is sending messages to lhc. I think you did not configured correctly mattermest part and it's not sending messages to lhc. You can verify that by checking server log on lhc side. Also watch youtube and check docs that you did not missed anything.

**Comment by remdex** [comment]
You should see in lhc http server log request comming to. If not you did not setup webhooks on mattermost


mattermost/callback

**Comment by nickian** [comment]
Oh ok, I figured it out, thanks. I re-watched the YouTube video. I missed a step with the new user I think. Works now!
